os:
  - linux

sudo: required

# install latest Tex Live
install:
  - curl -sSL https://raw.githubusercontent.com/ustctug/mini-texlive/master/install-tl.sh | sed 's!http://mirrors.ustc.edu.cn/CTAN!http://ctan.sharelatex.com/tex-archive!' | sudo bash
  - source ~/.bash_profile

# English fonts: replace Windows only fonts to TeX default fonts
before_script:
  - sed -i '/setmainfont/d' ustcthesis.cls
  - sed -i '/setsansfont/d' ustcthesis.cls
  - sed -i '/setmonofont/d' ustcthesis.cls

script:
  - make doc
  - make main
