os:
  - linux

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
  - bash ./support/texlive.sh
  - tlmgr update --self --all

# English fonts: replace Windows only fonts to TeX default fonts
before_script:
  - sed -i '/setmainfont/d' ustcthesis.dtx
  - sed -i '/setsansfont/d' ustcthesis.dtx
  - sed -i '/setmonofont/d' ustcthesis.dtx

script:
  - make main
  - sed -i 's/doctor/doctor,english/' main.tex
  - make main
  - sed -i 's/doctor,english/master/' main.tex
  - make main
  - sed -i 's/master/master,professional/' main.tex
  - make main
  - sed -i 's/master,professional/bachelor/' main.tex
  - make main
  - sed -i 's/bachelor/bachelor,english/' main.tex
  - make main
  - make doc
