name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install TeX Live
      run: |
        REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
        INSTALL="/tmp/install-texlive"
        mkdir -p $INSTALL
        curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL \
          --strip-components=1
        $INSTALL/install-tl -profile .github/workflows/texlive.profile
    - name: Install ustcthesis dependencies
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        tlmgr install latexmk l3build \
          fontname fontspec l3kernel l3packages xetex \
          cjk ctex environ ms trimspaces ulem xecjk zhnumber \
          caption filehook footmisc notoccite titlesec unicode-math \
          fandol tex-gyre xits \
          booktabs listings thumbpdf xcolor zapfding \
          algorithm2e ifoddpage nomencl relsize siunitx
    - name: Test thesis
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        make main
    - name: Test doc
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        make doc
    - name: Test formats
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        make test
